### ISSUE TITLE
Add rewrite rule to doxygen docs for convince

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#10]
It would be nice, to add rewrite rules to make access as this link:

http://docs.kicad-pcb.org/doxygen/v5_road_map.html#simulation

Go to

http://kicad-downloads.s3.cern.ch/doxygen/v5_road_map.html#simulation

I am not sure we can make a cname to the s3 bucket. I guess it becomes complicated with https. So doing a plain rewrite is probably good enough and it will let old reference work.

**Comment by marekr** [comment]
Nah it's fine even with https. 
We just mount /doxygen/ as a proxy rather than redirect. So we don't need a cname.
