### ISSUE TITLE
Redirect/rewrite URL directory to doc or rename app.html to index.html

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#13]
As mentioned in https://github.com/KiCad/kicad-doc-website/issues/8#issuecomment-459493901

The old "working" URL is not working anymore because the path to the actual docs has the format
`<host>/<version>/<language>/<app>/<app>.html`

While the old links worked with 
`<host>/<version>/<language>/<app>/`

Additionally the old site hosted the pdf and epub files as
`<host>/<version>/<language>/<app>.pdf`

Should we fix with with redirects or URL rewrites in the nginx conf or should we change the code that generates the site?

**Comment by extrapixel** [comment]
I recommend to implement the redirect. It can be done immediately and will work instantly. The decision and code change will take longer i guess. By the time the decision is made, search engines might have updated their indexes and we end up with 404s again.

**Comment by nickoe** [comment]
Please propose a patch, I don't have much time to muck around with it the next days, but I will be able to test it.
See https://github.com/KiCad/kicad-doc-website/blob/7e1e098d6b979f9d5365d0d3ef47f971545b63b5/.docker/default.conf
