### ISSUE TITLE
python documentation missing

### ISSUE THREAD

**Issue by MitjaNemec** [KiCad/kicad-doc-website#14]
I hope I am raising this in the correct repo.

I just found out that python [documentation](http://docs.kicad-pcb.org/doxygen-python/namespacepcbnew.html) is missing from the [website](http://docs.kicad-pcb.org/doxygen/md_Documentation_development_pcbnew-plugins.html) (the link in section `Existing Pcbnew Python API documentation`)

I haven't visited for quite some time, so I can not be specific, when it went missing

**Comment by nickoe** [comment]
Yes, you are correct, it is missing. I did this on purpose to see when someone would report it, and also because I did not prioritize it yet.

**Comment by MitjaNemec** [comment]
is it by any chance available on a build server like it used to be (I don't have the link anymore)

**Comment by nickoe** [comment]
It is available at https://kicad-downloads.s3.cern.ch/doxygen-python/index.html

**Comment by marekr** [comment]
I'll regex the current doxygen proxy rule to handle doxygen-python

**Comment by voneiden** [comment]
Still 404's. 

https://www.reddit.com/r/KiCad/comments/b81epd/broken_links_for_python_plugin_documentation/

**Comment by marekr** [comment]
Fixed in 67d881642f96d587af3a8730dae54901238d5521
