### ISSUE TITLE
Add new pcb calculator doc

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#16]
Do I need to add the new pcb calculator doc in this file?

https://github.com/KiCad/kicad-doc-website/blob/master/_source/_data/guide_priority.yml

Added in https://github.com/KiCad/kicad-doc/commit/ba1a72c3d1e8eef6d0e4183ac0a158a0731e6eb3

**Comment by marekr** [comment]
No, it'll just get lowest priority

**Comment by nickoe** [comment]
Mmm, ok, I see it in the app menu when on an app page, but not on the index page.

**Comment by marekr** [comment]
Maybe I fucked up

**Comment by marekr** [comment]
Since it's working....

**Comment by nickoe** [comment]
FWIW I think it iwas an issue with dockerhub building it, so it newer appeared at the expecred time.
