### ISSUE TITLE
Wonky URL is returned

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#2]
Sometimes it times out to an url like docs.test.kicad-pcb.org:8081/ja/, this is triggered by going to docs.test.kicad-pcb.org/ja. That is without a trailing slash. Maybe we need to add some url rewrite rule in the nginx conf.

**Comment by marekr** [comment]
Fixed in 646fbd3007c5e6d9f647ade105632120ee8b2eab
