### ISSUE TITLE
Wonkyness with the class images for doxygen-python

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#21]
In the kicad-doc-doxygen image the class png's are not available.

The doxygen stuff is built in
`.docker/Dockerfile.kicad-doc-doxygen
`
It is clear from the docker image, that the images are indeed missing.
`docker run -it kicadeda/kicad-docs-website ash -c 'find /usr/share/nginx/html/doxygen-python  -name "*png"'
`
It looks like the kicad build script is buggy or I call the wrong make targets.

```
make doxygen-docs
make doxygen-python
```

It looks like some dependencies are unstable? Sometimes I get ../build/pcbnew/doxygen-python and sometimes not...

If we do inspect the kicad-doc-doxygen image with a Dockerfile as:
```
FROM busybox
FROM kicadeda/kicad-doc-doxygen:master
COPY --from=0 / /
```

And run with:
`docker run -it <your_container_id> sh -c "ls doxygen-python_html |grep png"
`
We don't see the class png images.

I guess we should continue this on the bug tracker.

**Comment by marekr** [comment]
Pretty sure its a kicad repo issue and not the website :since it was doing it before with the uploads too.

**Comment by nickoe** [comment]
Maybe, or the build image. I do see errors about the `dot` command missing. I am not sure why that may mnot be an issue for the non python docs.

**Comment by nickoe** [comment]
Ok, it looks like it was indeed the dot command that was missing because graphviz was not installed.

Cmake did warn that doxygen did not have the dot command, but it didn't error.

So very soon it should work ok for the website, but I have not yet published the docker files for the build images. WIP.
