### ISSUE TITLE
jquery.min.map not found

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#6]
When run and accecessing something, I sometimes see this error in nginx:
`2019/01/14 16:47:58 [error] 8#8: *84 open() "/usr/share/nginx/html/js/jquery.min.map" failed (2: No such file or directory), client: 10.76.45.1, server: _, request: "GET /js/jquery.min.map HTTP/1.1", host: "docs.test.kicad-pcb.org"`

And this is what really is contained in the container:
```
/usr/share/nginx $ ls html/js/
bootstrap.min.js   cookieless.min.js  jquery.min.js      kicad.js
```

**Comment by marekr** [comment]
Accidentally fixed here.
https://github.com/marekr/kicad-doc-website/commit/632a30cb2c8ce8ce931db1cc5f7d9b24f0f3eb2f#diff-83aafa9af7c3df62e34b9c7ebb31e56eL5
