### ISSUE TITLE
Language select broken after url contains version

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#7]
It looks like the language select is broken. Selecting any language just goes to the <root-url>/<lang>, for example selecting french http://localhost:8081/fr, which just gives me a 404.

Going to http://localhost:8081/5.0.2/fr/ manually do show the correct index for the language.

Tested on 646fbd3007c5e6d9f647ade105632120ee8b2eab

**Comment by marekr** [comment]
Fixed 3358103501bdf23d62e536f3e0ac22843afd8771
