### ISSUE TITLE
A usability suggestion about the lang and version selectors

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-doc-website#8]
I think it would be nice UX if the version and language selectors would go to the same page as the reader is already on instead of jumping to the index page.

Say I am on http://localhost:8081/5.0.2/it/pl_editor/pl_editor.html

I would like to able to select the english language and it goes directly to http://localhost:8081/5.0.2/en/pl_editor/pl_editor.html instead of the index. (Though this is broken as of now according to https://github.com/marekr/kicad-doc-website/issues/7.

Tested on 646fbd3007c5e6d9f647ade105632120ee8b2eab

**Comment by marekr** [comment]
Yes its possible. Needs work because it needs to detect if the language and version exist for the guide.

**Comment by nickoe** [comment]
Yes, i understand that. I did think a bit about that, but I forgot to mention it.

I think a pretty 404 is an ok way to handle that, or go to the index for that given language. But ofc it gets a bit complex to handle it in the selector if we want to remove them here.

**Comment by marekr** [comment]
Done 632a30cb2c8ce8ce931db1cc5f7d9b24f0f3eb2f
Just more preprocessing

**Comment by nickoe** [comment]
It looks pretty good to me.

But I noticed that on the getting started guide the dutch lang is missing in the dropdown menu.

```
<li>
	<a href="/4.0.7/nl//getting_started_in_kicad/getting_started_in_kicad.html">
	<span></span>
	</a>
</li>

```

http://docs.test.kicad-pcb.org/4.0.7/en/getting_started_in_kicad/getting_started_in_kicad.html

Based on the image you pushed, sha256:4fa81866524cf8410a6f98cd27cd169d5d853310ac8c9d39348a4e5757f7b8da

**Comment by marekr** [comment]
The nl guide is being copied in accidentally. As far as I can tell, nobody actually translated anything besides putting their name on it. We don't even list it on the main website :P

**Comment by marekr** [comment]
https://github.com/KiCad/kicad-doc/blob/master/src/getting_started_in_kicad/po/nl.po

See, no translations.
It should be removed from kicad-doc.

**Comment by nickoe** [comment]
Hmm, ok. I guess I would simply have expected the menu to show it at least.

I see indeed that the translations are empty and they are not marked as fuzzy, so a bit strange. I will try to update that on master at least.

**Comment by nickoe** [comment]
About comment https://github.com/marekr/kicad-doc-website/issues/8#issuecomment-454645407, do you mean this issue is closed or are there still some things to do?

**Comment by marekr** [comment]
The menu is based on the list here:
https://github.com/marekr/kicad-doc-website/blob/master/_source/_data/language_definitions.yml

What's happening is its not finding a key for "nl".

**Comment by marekr** [comment]
The only thing left is debating the index page.

Like should the index for /5.0.2/en should all versions or just the ones that have "en".

But it may get confusing as the /5.0.2/en page looks just like the /5.0.2/ page and the same as the / page. lol

**Comment by nickoe** [comment]
Hmm, I am not sure I understand what you are suggesting. What do you mean with all versions? With 5.0.2/en it should show version 5.0.2 in english?

**Comment by extrapixel** [comment]
> I think a pretty 404 is an ok way to handle that, or go to the index for that given language. But ofc it gets a bit complex to handle it in the selector if we want to remove them here.

I strongly disagree. At the moment, most google results go to a sparse 404. An automated mapping / redirect should be put in place. At the minimum, users should get redirected to the language / version homepage. 
 
<img width="903" alt="screen shot 2019-01-31 at 21 12 10" src="https://user-images.githubusercontent.com/1862757/52083006-9b2d2b80-259e-11e9-899d-62da59696cad.png">

**Comment by extrapixel** [comment]
~~@nickoe - shall i open a new issue for the url redirect? still all old links are broken.~~ sry #13
